version: "3.8"

services: 
  db:
    image: postgres
    container_name: corelab_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: corelab_db
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - my-bridge-network

  app:
    build: .
    container_name: corelab_node
    command: ["yarn", "dev"]
    ports:
      - "3003:3003"
    volumes:
     - .:/usr/app
    networks:
      - my-bridge-network
    depends_on:
      - db

  
volumes:
  data: {}

networks:
  my-bridge-network:
    external: true