name: GitHub Actions WorkFlow

on: [pull_request, push]

jobs: 
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --ignore-engines # `yarn install`
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test # `yarn test`
      - name: Build the app
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc # `yarn tsc` 
